### PR TITLE
Fix of warning message, when using `onModalClosed` prop

### PR DESCRIPTION
**Pull request by georgii-nansen**
this PR fixes the following issues: 
https://github.com/coinbase/react-coinbase-commerce/issues/81
https://github.com/coinbase/react-coinbase-commerce/issues/23

### CODE REVIEW

**Comment by georgii-nansen** [comment]
@sds not sure who to mention here to bump this, so mentioning the latest contributor

**Comment by rrnara** [comment]
Can anyone review this, there's unnecessary console errors without this change

**Comment by gin** [comment]
@oa-coinbase @jakeleboeuf @ksmith-cb Please merge this fix 🙏

**Review by ksmithbaylor — APPROVED** [review]

**Comment by ksmithbaylor** [comment]
Hey! Sorry this took so long. We'll merge and publish this shortly.

**Review by sahil-cb — APPROVED** [review]

**Comment by beebikun** [comment]
Hello there! Any chance this can be merged? :)

**Review by ksmithbaylor — APPROVED** [review]

**Review by aarti — APPROVED** [review]

**Pull request merged**
